### ISSUE TITLE
How to stop TS Lint from from complaining about "app" being prefix for component or directive selectors?

### ISSUE THREAD

**Issue by praveenpuglia** [praveenpuglia/angular-sanity#2]
## Original Error
```
[TSLint] The selector of the component "AppComponent" should have prefix "app"
```
In `tslint.json` for these two entries, replace `"app"` with any prefix of your choice.
```json
"directive-selector": [true, "attribute", "app", "camelCase"],
"component-selector": [true, "element", "app", "kebab-case"],
```

Courtesy - https://stackoverflow.com/questions/41248142/angular2-how-to-change-the-default-prefix-of-component-to-stop-tslint-warnings

**Comment by ghost** [comment]
thanks!

**Comment by RushuiGuan** [comment]
What if I want to have different prefix in an app?

**Comment by JoshK2** [comment]
thanks!
