### ISSUE TITLE
How to fix TSLint: " should be ' (quotemark) while doing organize imports in code editors?

### ISSUE THREAD

**Issue by praveenpuglia** [praveenpuglia/angular-sanity#4]
Basically this.
![image](https://user-images.githubusercontent.com/313363/29157485-bf56b7ca-7dc4-11e7-8562-93d3d9f4c9bc.png)

## WebStorm
By default, WebStorm is configured to insert automatic import statements with double quotes. TS Lint complains about it. 

## Fix
**Preferences** > **Editor** > **Code Style** > **TypeScript** > **Punctuation** > _Use `single` quotes in new code_

<img width="1134" alt="pasted_image_8_10_17__12_08_pm" src="https://user-images.githubusercontent.com/313363/29157602-31e3733c-7dc5-11e7-91f9-1dd9f05b5a40.png">

If you are on an older version of WebStorm, you may not find the **Punctuation** tab. Look for the setting in Others section.

## VSCode
Auto imports are intelligent in VSCode to use `tslint.json` file in order to insert import statements based on your configuration. But if you are manually writing import statement and accidentally mess that up here's one thing to rescue.

In **User Preferences** set the following.
```json
"tslint.autoFixOnSave": true
```
Courtesy - https://github.com/Microsoft/vscode/issues/21424#issuecomment-282524286

It's delightful. 😊

**Comment by sudodaksh** [comment]
@praveenpuglia can you please share your webstormconfig? I really like it :D

**Comment by praveenpuglia** [comment]
Hey @DakshMiglani 
I think I was using the material theme for webstorm. https://github.com/ChrisRM/material-theme-jetbrains

Along with **Roboto Mono** - 14px. Make sure your webstorm is the latest one and you have Java8 so you get real good font rendering.

**Comment by praveenpuglia** [comment]
Also, if you like the issues that have been posted here, feel free to star this repository. That'll be a great encouragement to me! :)

**Comment by sudodaksh** [comment]
@praveenpuglia linux user here, font management sucks xD

**Comment by peterremote1980** [comment]
not working
![untitled](https://user-images.githubusercontent.com/36571333/47255411-7c999d80-d4a3-11e8-8a95-45b01ee17153.png)

**Comment by praveenpuglia** [comment]
@peterremote1980 can you please post your typescript and vscode versions? it should just work and it still works for me in my projects. 

Can you also tell me which typescript related plugins you are using?

**Comment by vyushin** [comment]
@peterremote1980, why tsconfig.json on screenshot has 3 level nesting? This is strange. The `rules` should be on first level nesting. Like this:
```json
{
  "rules": {
    "quotemark": [true, "single", "avoid-escape"]
  }
}
```
It works :)
