### ISSUE TITLE
How to do if then else in templates when you can't apply multiple template bindings to one element?

### ISSUE THREAD

**Issue by praveenpuglia** [praveenpuglia/angular-sanity#6]
We get that error when we try to use, say - `*ngIf` and `*ngFor` on the same template. Due to this, we can't do something like this.
```html
<li *ngIf="editable" *ngFor="let item of items" class="editable">...</li>
<li *ngIf="!editable" *ngFor="let item of items" class="non-editable">...</li>

<!-- OR -->
<li *ngIf="editable; else #viewOnlyList" *ngFor="let item of items" class="editable">...</li>
<ng-template #viewOnlyList>
  <li *ngFor="let item of items" class="non-editable">...</li>
</ng-template>
```

To get around this, use an `<ng-container>` or any other element that can hold the if condition and then use two `<ng-template>` tags to nest different templates.

```html
<!-- Angular will not render this element at all -->
<!-- I know it feels hacky -->
<ng-container *ngIf="editable; then editableList else viewOnlyList"></ng-container>

<ng-template #editableList>
  <li *ngFor="let item of items" class="editable">...</li>
</ng-template>

<ng-template #viewOnlyList>
  <li *ngFor="let item of items" class="non-editable">...</li>
</ng-template>
```

**Comment by nadiamechlia** [comment]
you could simply user [ngCLass], first you should as two class to your style 'editable' with 'color: green' and 'non-editable' with 'color: red' as below : 
style.scss file:
`.editable {
      color: green;
}
.non-editable {
   color: red;
}
`
and then use [ngCLass] in your html file: 
`<li *ngFor="let item of items" [ngCLass]="{editable?:'editable':'non-editable'}">...</li>`

**Comment by praveenpuglia** [comment]
How is `ngClass` related to this? I really wanna have an element on DOM or not. Even if I do `display: none` via some class, I'll still have the elements on DOM.

**Comment by nadiamechlia** [comment]
if you want send me a bunch of your code to take a look ... it works for me

**Comment by ashikjs** [comment]
I got this nice solution from
[stackoverflow Q Answer By Imal hasaranga perera](https://stackoverflow.com/questions/34657821/ngif-and-ngfor-on-same-element-causing-error
)
```
<ng-container *ngFor="let nav_link of defaultLinks" >
   <li *ngIf="nav_link.visible">
       .....
   </li> 
</ng-container>
```
